// Generated by CoffeeScript 1.7.1
(function() {
  var FileFinder, file, finder, program;

  program = require("commander");

  FileFinder = require("./FileFinder").FileFinder;

  program.version("0.0.1").option("-w, --watch", "Watch Files").parse(process.argv);

  file = process.argv[process.argv.length - 1];

  if (!program.watch) {
    finder = new FileFinder(file);
    console.log(finder.getAbsolutePath());
  }

}).call(this);
