// Generated by CoffeeScript 1.7.1
(function() {
  var Include;

  Include = (function() {
    function Include(required, caller) {
      this.required = required;
      this.caller = caller;
    }

    return Include;

  })();

  if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
    module.exports.Include = Include;
  }

}).call(this);
